version: '3' # docker compose version
volumes:
  dataPostgre:
networks: 
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6 # image
    volumes: # db service volumes 
      - dataPostgre:/var/lib/postgresql/data # data volumes 
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - banco  
  frontend:
    image: nginx:1.13
    volumes: 
      - ./web:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    networks: 
      - web
    depends_on: 
      - app    
  app:
    image: python:3.6
    volumes:
      - ./app:/app 
    working_dir: /app
    command: bash ./app.sh
    networks: 
      - web
      - banco
      - fila
    depends_on: 
      - db
      - queue
  queue:
    image: redis:3.2
    networks: 
      - fila
  worker:
    build: worker
    volumes:
       - ./worker:/worker
    working_dir: /worker 
    command: worker.py
    networks: 
      - fila
    depends_on: 
      - queue  
               