version: '3'
services: 
  nginx:
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: robson/nginx
    container_name: nginx
    ports: 
      - 80:80
    depends_on:  
      - "node1"
      - "node2"
      - "node3"    
    networks: 
      - production-network

  mongodb:
    image: mongo
    networks: 
      - production-network

  node1:
    build: 
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: robson/alura-books
    container_name: alura-books1
    ports: 
      - "3000"
    networks: 
      - production-network
    depends_on:  
      - "mongodb"    

  node2:
    build: 
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: robson/alura-books
    container_name: alura-books2
    ports: 
      - "3000"
    networks: 
      - production-network    
    depends_on:  
      - "mongodb"  

  node3:
    build: 
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: robson/alura-books
    container_name: alura-books
    ports: 
      - "3000"
    networks: 
      - production-network    
    depends_on:  
      - "mongodb"

networks: 
    production-network:
      driver: bridge